import { db } from "../src/database/connection"
import { platformUsers, platformUserProfiles } from "../src/database/schema/platform-user"
import bcrypt from "bcrypt"
import { faker } from '@faker-js/faker';
async function seedPlatformUsers() {
    console.log("🌱 Starting platform users seeding...")

    try {
        // Hash password for all users
        const hashedPassword = await bcrypt.hash("User@123", 10)

        // Generate UUIDs for users
        const userIds = {
            rajeshKumar: crypto.randomUUID(),
            priyaSharma: crypto.randomUUID(),
            amitPatel: crypto.randomUUID(),
            sunitaSingh: crypto.randomUUID(),
            vikramGupta: crypto.randomUUID(),
            deepakAgent: crypto.randomUUID(),
            kavitaAgent: crypto.randomUUID(),
            rohitAgent: crypto.randomUUID(),
            nehaAgent: crypto.randomUUID(),
            sanjayAgent: crypto.randomUUID(),
            ankitUser: crypto.randomUUID(),
            poojaUser: crypto.randomUUID(),
            rahulUser: crypto.randomUUID(),
            meeraUser: crypto.randomUUID(),
            karanUser: crypto.randomUUID(),
        }

        // Insert platform users
        await db.insert(platformUsers).values([
            // Property Owners
            {
                id: userIds.rajeshKumar,
                uuid: crypto.randomUUID(),
                email: "rajesh.kumar@email.com",
                firstName: "Rajesh",
                lastName: "Kumar",
                password: hashedPassword,
                role: "owner",
                isActive: true,
                isVerified: true,
                emailVerifiedAt: new Date("2024-01-15T10:30:00Z"),
                lastLoginAt: new Date("2024-01-20T14:22:00Z"),
                twoFactorEnabled: false,
                companyName: "Kumar Properties",
                businessType: "individual",
                taxId: "07ABCDE1234F1Z5",
                createdAt: new Date("2024-01-10T09:00:00Z"),
                updatedAt: new Date("2024-01-20T14:22:00Z"),
            },
            {
                id: userIds.priyaSharma,
                uuid: crypto.randomUUID(),
                email: "priya.sharma@email.com",
                firstName: "Priya",
                lastName: "Sharma",
                password: hashedPassword,
                role: "owner",
                isActive: true,
                isVerified: true,
                emailVerifiedAt: new Date("2024-01-12T11:15:00Z"),
                lastLoginAt: new Date("2024-01-19T16:45:00Z"),
                twoFactorEnabled: true,
                companyName: "Sharma Residences",
                businessType: "individual",
                taxId: "07FGHIJ5678K2L6",
                createdAt: new Date("2024-01-08T10:30:00Z"),
                updatedAt: new Date("2024-01-19T16:45:00Z"),
            },
            {
                id: userIds.amitPatel,
                uuid: crypto.randomUUID(),
                email: "amit.patel@email.com",
                firstName: "Amit",
                lastName: "Patel",
                password: hashedPassword,
                role: "owner",
                isActive: true,
                isVerified: true,
                emailVerifiedAt: new Date("2024-01-14T09:20:00Z"),
                lastLoginAt: new Date("2024-01-21T11:30:00Z"),
                twoFactorEnabled: false,
                companyName: "Patel Commercial Ventures",
                businessType: "company",
                taxId: "27MNOPQ9012R3S7",
                createdAt: new Date("2024-01-05T14:15:00Z"),
                updatedAt: new Date("2024-01-21T11:30:00Z"),
            },
            {
                id: userIds.sunitaSingh,
                uuid: crypto.randomUUID(),
                email: "sunita.singh@email.com",
                firstName: "Sunita",
                lastName: "Singh",
                password: hashedPassword,
                role: "owner",
                isActive: true,
                isVerified: true,
                emailVerifiedAt: new Date("2024-01-16T13:45:00Z"),
                lastLoginAt: new Date("2024-01-20T09:15:00Z"),
                twoFactorEnabled: false,
                companyName: "Singh Farmhouses",
                businessType: "individual",
                taxId: "06TUVWX3456Y4Z8",
                createdAt: new Date("2024-01-12T11:00:00Z"),
                updatedAt: new Date("2024-01-20T09:15:00Z"),
            },
            {
                id: userIds.vikramGupta,
                uuid: crypto.randomUUID(),
                email: "vikram.gupta@email.com",
                firstName: "Vikram",
                lastName: "Gupta",
                password: hashedPassword,
                role: "owner",
                isActive: true,
                isVerified: false,
                emailVerifiedAt: null,
                lastLoginAt: new Date("2024-01-18T15:30:00Z"),
                twoFactorEnabled: false,
                companyName: "Gupta Land Developers",
                businessType: "partnership",
                taxId: "06ABCDE7890F5G9",
                createdAt: new Date("2024-01-15T16:20:00Z"),
                updatedAt: new Date("2024-01-18T15:30:00Z"),
            },

            // Real Estate Agents
            {
                id: userIds.deepakAgent,
                uuid: crypto.randomUUID(),
                email: "deepak@deepakrealty.com",
                firstName: "Deepak",
                lastName: "Agarwal",
                password: hashedPassword,
                role: "agent",
                isActive: true,
                isVerified: true,
                emailVerifiedAt: new Date("2024-01-08T10:00:00Z"),
                lastLoginAt: new Date("2024-01-21T08:45:00Z"),
                twoFactorEnabled: true,
                licenseNumber: "REA/DL/2023/1001",
                companyName: "Deepak Realty Solutions",
                businessType: "company",
                taxId: "07HIJKL1234M6N0",
                createdAt: new Date("2024-01-05T09:30:00Z"),
                updatedAt: new Date("2024-01-21T08:45:00Z"),
            },
            {
                id: userIds.kavitaAgent,
                uuid: crypto.randomUUID(),
                email: "kavita@kavitaproperties.com",
                firstName: "Kavita",
                lastName: "Mehta",
                password: hashedPassword,
                role: "agent",
                isActive: true,
                isVerified: true,
                emailVerifiedAt: new Date("2024-01-10T12:30:00Z"),
                lastLoginAt: new Date("2024-01-20T17:20:00Z"),
                twoFactorEnabled: false,
                licenseNumber: "REA/DL/2023/1002",
                companyName: "Kavita Properties & Associates",
                businessType: "partnership",
                taxId: "07OPQRS5678T7U1",
                createdAt: new Date("2024-01-07T11:15:00Z"),
                updatedAt: new Date("2024-01-20T17:20:00Z"),
            },
            {
                id: userIds.rohitAgent,
                uuid: crypto.randomUUID(),
                email: "rohit@rohitestates.com",
                firstName: "Rohit",
                lastName: "Malhotra",
                password: hashedPassword,
                role: "agent",
                isActive: true,
                isVerified: true,
                emailVerifiedAt: new Date("2024-01-11T14:15:00Z"),
                lastLoginAt: new Date("2024-01-19T12:10:00Z"),
                twoFactorEnabled: true,
                licenseNumber: "REA/DL/2023/1003",
                companyName: "Rohit Luxury Estates",
                businessType: "company",
                taxId: "07VWXYZ9012A8B2",
                createdAt: new Date("2024-01-09T13:45:00Z"),
                updatedAt: new Date("2024-01-19T12:10:00Z"),
            },
            {
                id: userIds.nehaAgent,
                uuid: crypto.randomUUID(),
                email: "neha@neharealestate.com",
                firstName: "Neha",
                lastName: "Kapoor",
                password: hashedPassword,
                role: "agent",
                isActive: true,
                isVerified: true,
                emailVerifiedAt: new Date("2024-01-13T16:00:00Z"),
                lastLoginAt: new Date("2024-01-21T10:30:00Z"),
                twoFactorEnabled: false,
                licenseNumber: "REA/DL/2023/1004",
                companyName: "Neha Real Estate Consultancy",
                businessType: "individual",
                taxId: "07CDEFG3456H9I3",
                createdAt: new Date("2024-01-11T15:20:00Z"),
                updatedAt: new Date("2024-01-21T10:30:00Z"),
            },
            {
                id: userIds.sanjayAgent,
                uuid: crypto.randomUUID(),
                email: "sanjay@sanjayproperties.com",
                firstName: "Sanjay",
                lastName: "Joshi",
                password: hashedPassword,
                role: "agent",
                isActive: true,
                isVerified: true,
                emailVerifiedAt: new Date("2024-01-06T09:45:00Z"),
                lastLoginAt: new Date("2024-01-20T14:55:00Z"),
                twoFactorEnabled: true,
                licenseNumber: "REA/DL/2023/1005",
                companyName: "Sanjay Properties & Investments",
                businessType: "company",
                taxId: "07JKLMN7890O0P4",
                createdAt: new Date("2024-01-03T10:10:00Z"),
                updatedAt: new Date("2024-01-20T14:55:00Z"),
            },

            // Regular Users
            {
                id: userIds.ankitUser,
                uuid: crypto.randomUUID(),
                email: "ankit.verma@email.com",
                firstName: "Ankit",
                lastName: "Verma",
                password: hashedPassword,
                role: "user",
                isActive: true,
                isVerified: true,
                emailVerifiedAt: new Date("2024-01-17T11:20:00Z"),
                lastLoginAt: new Date("2024-01-21T09:40:00Z"),
                twoFactorEnabled: false,
                createdAt: new Date("2024-01-14T12:30:00Z"),
                updatedAt: new Date("2024-01-21T09:40:00Z"),
            },
            {
                id: userIds.poojaUser,
                uuid: crypto.randomUUID(),
                email: "pooja.agarwal@email.com",
                firstName: "Pooja",
                lastName: "Agarwal",
                password: hashedPassword,
                role: "user",
                isActive: true,
                isVerified: true,
                emailVerifiedAt: new Date("2024-01-18T13:10:00Z"),
                lastLoginAt: new Date("2024-01-20T16:25:00Z"),
                twoFactorEnabled: true,
                createdAt: new Date("2024-01-16T14:45:00Z"),
                updatedAt: new Date("2024-01-20T16:25:00Z"),
            },
            {
                id: userIds.rahulUser,
                uuid: crypto.randomUUID(),
                email: "rahul.jain@email.com",
                firstName: "Rahul",
                lastName: "Jain",
                password: hashedPassword,
                role: "user",
                isActive: true,
                isVerified: false,
                emailVerifiedAt: null,
                lastLoginAt: new Date("2024-01-19T10:15:00Z"),
                twoFactorEnabled: false,
                createdAt: new Date("2024-01-17T09:20:00Z"),
                updatedAt: new Date("2024-01-19T10:15:00Z"),
            },
            {
                id: userIds.meeraUser,
                uuid: crypto.randomUUID(),
                email: "meera.reddy@email.com",
                firstName: "Meera",
                lastName: "Reddy",
                password: hashedPassword,
                role: "user",
                isActive: true,
                isVerified: true,
                emailVerifiedAt: new Date("2024-01-19T15:30:00Z"),
                lastLoginAt: new Date("2024-01-21T11:50:00Z"),
                twoFactorEnabled: false,
                createdAt: new Date("2024-01-18T16:10:00Z"),
                updatedAt: new Date("2024-01-21T11:50:00Z"),
            },
            {
                id: userIds.karanUser,
                uuid: crypto.randomUUID(),
                email: "karan.malhotra@email.com",
                firstName: "Karan",
                lastName: "Malhotra",
                password: hashedPassword,
                role: "user",
                isActive: true,
                isVerified: true,
                emailVerifiedAt: new Date("2024-01-20T12:45:00Z"),
                lastLoginAt: new Date("2024-01-21T13:20:00Z"),
                twoFactorEnabled: true,
                createdAt: new Date("2024-01-19T11:30:00Z"),
                updatedAt: new Date("2024-01-21T13:20:00Z"),
            },
        ])

        console.log("✅ Platform users inserted successfully")

        // Insert platform user profiles
        await db.insert(platformUserProfiles).values([
            // Property Owner Profiles
            {
                id: crypto.randomUUID(),
                userId: userIds.rajeshKumar,
                bio: "Experienced property owner with multiple residential properties in Gurgaon. Specializing in premium villa rentals and sales.",
                avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
                phone: "+91-9876543210",
                address: "Sector 47, DLF Phase 4",
                city: "Gurgaon",
                state: "Haryana",
                country: "India",
                pincode: "122009",
                website: "https://kumarproperties.com",
                socialLinks: {
                    linkedin: "https://linkedin.com/in/rajesh-kumar-properties",
                    facebook: "https://facebook.com/kumarproperties",
                    instagram: "https://instagram.com/kumar_properties",
                },
                preferences: {
                    notifications: { email: true, sms: true, push: true },
                    privacy: { showPhone: true, showEmail: false },
                    communication: { preferredTime: "morning", language: "hindi" },
                },
                specializations: ["residential", "villa", "luxury"],
                serviceAreas: ["Gurgaon", "New Delhi", "Faridabad"],
                languages: ["Hindi", "English", "Punjabi"],
                experience: "12",
                rating: "4.6",
                totalReviews: 28,
                createdAt: new Date("2024-01-10T09:00:00Z"),
                updatedAt: new Date("2024-01-20T14:22:00Z"),
            },
            {
                id: crypto.randomUUID(),
                userId: userIds.priyaSharma,
                bio: "Property owner and interior designer with a keen eye for modern apartment living. Owner of premium apartments in Noida.",
                avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face",
                phone: "+91-9876543211",
                address: "Sector 62, Noida",
                city: "Noida",
                state: "Uttar Pradesh",
                country: "India",
                pincode: "201309",
                website: "https://sharmaresidences.com",
                socialLinks: {
                    linkedin: "https://linkedin.com/in/priya-sharma-properties",
                    instagram: "https://instagram.com/sharma_residences",
                },
                preferences: {
                    notifications: { email: true, sms: false, push: true },
                    privacy: { showPhone: true, showEmail: true },
                    communication: { preferredTime: "evening", language: "english" },
                },
                specializations: ["residential", "apartment", "modern"],
                serviceAreas: ["Noida", "Greater Noida", "Ghaziabad"],
                languages: ["Hindi", "English"],
                experience: "8",
                rating: "4.4",
                totalReviews: 15,
                createdAt: new Date("2024-01-08T10:30:00Z"),
                updatedAt: new Date("2024-01-19T16:45:00Z"),
            },
            {
                id: crypto.randomUUID(),
                userId: userIds.amitPatel,
                bio: "Commercial property investor and owner with extensive portfolio in Mumbai's business districts. Expert in office spaces and retail.",
                avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
                phone: "+91-9876543212",
                address: "Andheri East, Mumbai",
                city: "Mumbai",
                state: "Maharashtra",
                country: "India",
                pincode: "400069",
                website: "https://patelcommercial.com",
                socialLinks: {
                    linkedin: "https://linkedin.com/in/amit-patel-commercial",
                    twitter: "https://twitter.com/amitpatel_realty",
                },
                preferences: {
                    notifications: { email: true, sms: true, push: false },
                    privacy: { showPhone: false, showEmail: true },
                    communication: { preferredTime: "business_hours", language: "english" },
                },
                specializations: ["commercial", "office", "retail"],
                serviceAreas: ["Mumbai", "Navi Mumbai", "Thane"],
                languages: ["Hindi", "English", "Gujarati"],
                experience: "15",
                rating: "4.7",
                totalReviews: 42,
                createdAt: new Date("2024-01-05T14:15:00Z"),
                updatedAt: new Date("2024-01-21T11:30:00Z"),
            },
            {
                id: crypto.randomUUID(),
                userId: userIds.sunitaSingh,
                bio: "Farmhouse and agricultural property owner specializing in weekend retreats and agricultural investments in NCR region.",
                avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
                phone: "+91-9876543213",
                address: "Sector 81, Faridabad",
                city: "Faridabad",
                state: "Haryana",
                country: "India",
                pincode: "121004",
                socialLinks: {
                    facebook: "https://facebook.com/singh.farmhouses",
                },
                preferences: {
                    notifications: { email: true, sms: true, push: false },
                    privacy: { showPhone: true, showEmail: false },
                    communication: { preferredTime: "morning", language: "hindi" },
                },
                specializations: ["agricultural", "farmhouse", "weekend_retreat"],
                serviceAreas: ["Faridabad", "Gurgaon", "Palwal"],
                languages: ["Hindi", "English"],
                experience: "10",
                rating: "4.3",
                totalReviews: 12,
                createdAt: new Date("2024-01-12T11:00:00Z"),
                updatedAt: new Date("2024-01-20T09:15:00Z"),
            },
            {
                id: crypto.randomUUID(),
                userId: userIds.vikramGupta,
                bio: "Land developer and plot owner with prime residential and commercial plots in emerging areas of NCR.",
                avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
                phone: "+91-9876543214",
                address: "Sector 5, Manesar",
                city: "Manesar",
                state: "Haryana",
                country: "India",
                pincode: "122051",
                preferences: {
                    notifications: { email: true, sms: false, push: true },
                    privacy: { showPhone: true, showEmail: true },
                    communication: { preferredTime: "afternoon", language: "hindi" },
                },
                specializations: ["plot", "land_development", "investment"],
                serviceAreas: ["Manesar", "Gurgaon", "Rewari"],
                languages: ["Hindi", "English"],
                experience: "6",
                rating: "4.1",
                totalReviews: 8,
                createdAt: new Date("2024-01-15T16:20:00Z"),
                updatedAt: new Date("2024-01-18T15:30:00Z"),
            },

            // Real Estate Agent Profiles
            {
                id: crypto.randomUUID(),
                userId: userIds.deepakAgent,
                bio: "Licensed real estate agent with 15+ years of experience in residential properties. Specializing in first-time home buyers and family homes in NCR.",
                avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop&crop=face",
                phone: "+91-9876543215",
                address: "Sector 14, Gurgaon",
                city: "Gurgaon",
                state: "Haryana",
                country: "India",
                pincode: "122001",
                website: "https://deepakrealty.com",
                socialLinks: {
                    linkedin: "https://linkedin.com/in/deepak-agarwal-realty",
                    facebook: "https://facebook.com/deepakrealtysolutions",
                    instagram: "https://instagram.com/deepak_realty",
                },
                preferences: {
                    notifications: { email: true, sms: true, push: true },
                    privacy: { showPhone: true, showEmail: true },
                    communication: { preferredTime: "business_hours", language: "both" },
                },
                specializations: ["residential", "apartment", "villa", "first_time_buyers"],
                serviceAreas: ["Gurgaon", "New Delhi", "Faridabad", "Noida"],
                languages: ["Hindi", "English", "Punjabi"],
                experience: "15",
                rating: "4.8",
                totalReviews: 156,
                createdAt: new Date("2024-01-05T09:30:00Z"),
                updatedAt: new Date("2024-01-21T08:45:00Z"),
            },
            {
                id: crypto.randomUUID(),
                userId: userIds.kavitaAgent,
                bio: "Commercial real estate specialist with expertise in office spaces, retail outlets, and business investments. 12 years of proven track record.",
                avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&h=150&fit=crop&crop=face",
                phone: "+91-9876543216",
                address: "Cyber City, Gurgaon",
                city: "Gurgaon",
                state: "Haryana",
                country: "India",
                pincode: "122002",
                website: "https://kavitaproperties.com",
                socialLinks: {
                    linkedin: "https://linkedin.com/in/kavita-mehta-commercial",
                    twitter: "https://twitter.com/kavita_properties",
                },
                preferences: {
                    notifications: { email: true, sms: false, push: true },
                    privacy: { showPhone: true, showEmail: true },
                    communication: { preferredTime: "business_hours", language: "english" },
                },
                specializations: ["commercial", "office", "retail", "investment"],
                serviceAreas: ["Gurgaon", "New Delhi", "Noida", "Faridabad"],
                languages: ["Hindi", "English"],
                experience: "12",
                rating: "4.6",
                totalReviews: 89,
                createdAt: new Date("2024-01-07T11:15:00Z"),
                updatedAt: new Date("2024-01-20T17:20:00Z"),
            },
            {
                id: crypto.randomUUID(),
                userId: userIds.rohitAgent,
                bio: "Luxury property specialist focusing on high-end villas, penthouses, and premium residential projects. Serving affluent clients for over 10 years.",
                avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=face",
                phone: "+91-9876543217",
                address: "Golf Course Road, Gurgaon",
                city: "Gurgaon",
                state: "Haryana",
                country: "India",
                pincode: "122007",
                website: "https://rohitluxuryestates.com",
                socialLinks: {
                    linkedin: "https://linkedin.com/in/rohit-malhotra-luxury",
                    instagram: "https://instagram.com/rohit_luxury_estates",
                },
                preferences: {
                    notifications: { email: true, sms: true, push: true },
                    privacy: { showPhone: true, showEmail: true },
                    communication: { preferredTime: "flexible", language: "english" },
                },
                specializations: ["luxury", "villa", "penthouse", "premium"],
                serviceAreas: ["Gurgaon", "New Delhi", "Mumbai", "Bangalore"],
                languages: ["Hindi", "English"],
                experience: "10",
                rating: "4.7",
                totalReviews: 67,
                createdAt: new Date("2024-01-09T13:45:00Z"),
                updatedAt: new Date("2024-01-19T12:10:00Z"),
            },
            {
                id: crypto.randomUUID(),
                userId: userIds.nehaAgent,
                bio: "Dedicated real estate consultant specializing in helping first-time home buyers navigate the property market. Known for patient guidance and transparent dealings.",
                avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face",
                phone: "+91-9876543218",
                address: "Sector 29, Gurgaon",
                city: "Gurgaon",
                state: "Haryana",
                country: "India",
                pincode: "122001",
                website: "https://neharealestate.com",
                socialLinks: {
                    linkedin: "https://linkedin.com/in/neha-kapoor-realestate",
                    facebook: "https://facebook.com/neharealestatecons",
                },
                preferences: {
                    notifications: { email: true, sms: true, push: false },
                    privacy: { showPhone: true, showEmail: true },
                    communication: { preferredTime: "morning_evening", language: "both" },
                },
                specializations: ["residential", "first_time_buyers", "affordable_housing", "consultation"],
                serviceAreas: ["Gurgaon", "Faridabad", "New Delhi"],
                languages: ["Hindi", "English"],
                experience: "8",
                rating: "4.5",
                totalReviews: 94,
                createdAt: new Date("2024-01-11T15:20:00Z"),
                updatedAt: new Date("2024-01-21T10:30:00Z"),
            },
            {
                id: crypto.randomUUID(),
                userId: userIds.sanjayAgent,
                bio: "Senior real estate professional with 20+ years of experience in property investments, portfolio management, and wealth creation through real estate.",
                avatar: "https://images.unsplash.com/photo-1556157382-97eda2d62296?w=150&h=150&fit=crop&crop=face",
                phone: "+91-9876543219",
                address: "Connaught Place, New Delhi",
                city: "New Delhi",
                state: "Delhi",
                country: "India",
                pincode: "110001",
                website: "https://sanjayproperties.com",
                socialLinks: {
                    linkedin: "https://linkedin.com/in/sanjay-joshi-investments",
                    twitter: "https://twitter.com/sanjay_properties",
                },
                preferences: {
                    notifications: { email: true, sms: true, push: true },
                    privacy: { showPhone: true, showEmail: true },
                    communication: { preferredTime: "business_hours", language: "both" },
                },
                specializations: ["investment", "portfolio_management", "commercial", "residential"],
                serviceAreas: ["New Delhi", "Gurgaon", "Noida", "Faridabad", "Mumbai"],
                languages: ["Hindi", "English", "Marathi"],
                experience: "20",
                rating: "4.8",
                totalReviews: 203,
                createdAt: new Date("2024-01-03T10:10:00Z"),
                updatedAt: new Date("2024-01-20T14:55:00Z"),
            },

            // Regular User Profiles
            {
                id: crypto.randomUUID(),
                userId: userIds.ankitUser,
                bio: "Software engineer looking for my first home in NCR. Interested in modern apartments with good connectivity to tech hubs.",
                avatar: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=150&h=150&fit=crop&crop=face",
                phone: "+91-9876543220",
                address: "Sector 18, Noida",
                city: "Noida",
                state: "Uttar Pradesh",
                country: "India",
                pincode: "201301",
                preferences: {
                    notifications: { email: true, sms: false, push: true },
                    privacy: { showPhone: false, showEmail: false },
                    communication: { preferredTime: "evening", language: "english" },
                },
                createdAt: new Date("2024-01-14T12:30:00Z"),
                updatedAt: new Date("2024-01-21T09:40:00Z"),
            },
            {
                id: crypto.randomUUID(),
                userId: userIds.poojaUser,
                bio: "Investment banker interested in property investments and rental income opportunities. Looking for high-ROI properties in prime locations.",
                avatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop&crop=face",
                phone: "+91-9876543221",
                address: "Vasant Kunj, New Delhi",
                city: "New Delhi",
                state: "Delhi",
                country: "India",
                pincode: "110070",
                preferences: {
                    notifications: { email: true, sms: true, push: true },
                    privacy: { showPhone: false, showEmail: true },
                    communication: { preferredTime: "business_hours", language: "english" },
                },
                createdAt: new Date("2024-01-16T14:45:00Z"),
                updatedAt: new Date("2024-01-20T16:25:00Z"),
            },
            {
                id: crypto.randomUUID(),
                userId: userIds.rahulUser,
                bio: "Entrepreneur seeking commercial office space for expanding business. Interested in modern office complexes with good infrastructure.",
                avatar: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=150&h=150&fit=crop&crop=face",
                phone: "+91-9876543222",
                address: "Rajouri Garden, New Delhi",
                city: "New Delhi",
                state: "Delhi",
                country: "India",
                pincode: "110027",
                preferences: {
                    notifications: { email: true, sms: false, push: false },
                    privacy: { showPhone: true, showEmail: false },
                    communication: { preferredTime: "business_hours", language: "hindi" },
                },
                createdAt: new Date("2024-01-17T09:20:00Z"),
                updatedAt: new Date("2024-01-19T10:15:00Z"),
            },
            {
                id: crypto.randomUUID(),
                userId: userIds.meeraUser,
                bio: "Marketing professional relocating to NCR, looking for rental apartments with modern amenities and good connectivity to metro stations.",
                avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face",
                phone: "+91-9876543223",
                address: "Koramangala, Bangalore",
                city: "Bangalore",
                state: "Karnataka",
                country: "India",
                pincode: "560034",
                preferences: {
                    notifications: { email: true, sms: true, push: false },
                    privacy: { showPhone: true, showEmail: true },
                    communication: { preferredTime: "evening", language: "english" },
                },
                createdAt: new Date("2024-01-18T16:10:00Z"),
                updatedAt: new Date("2024-01-21T11:50:00Z"),
            },
            {
                id: crypto.randomUUID(),
                userId: userIds.karanUser,
                bio: "Luxury car dealer interested in premium properties and high-end real estate investments. Looking for exclusive properties in prime locations.",
                avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
                phone: "+91-9876543224",
                address: "Bandra West, Mumbai",
                city: "Mumbai",
                state: "Maharashtra",
                country: "India",
                pincode: "400050",
                preferences: {
                    notifications: { email: true, sms: true, push: true },
                    privacy: { showPhone: true, showEmail: true },
                    communication: { preferredTime: "flexible", language: "english" },
                },
                createdAt: new Date("2024-01-19T11:30:00Z"),
                updatedAt: new Date("2024-01-21T13:20:00Z"),
            },
        ])

        console.log("✅ Platform user profiles inserted successfully")
        console.log("🎉 Platform users seeding completed!")
        console.log("\n📊 Seeded Data Summary:")
        console.log("- Property Owners: 5 users")
        console.log("- Real Estate Agents: 5 users")
        console.log("- Regular Users: 5 users")
        console.log("- Total Users: 15 users")
        console.log("- Verified Users: 12 users")
        console.log("- Users with 2FA: 6 users")
        console.log("\n🔐 Login Credentials:")
        console.log("Password for all users: User@123")
        console.log("\n📧 Sample Login Emails:")
        console.log("- rajesh.kumar@email.com (Property Owner)")
        console.log("- deepak@deepakrealty.com (Real Estate Agent)")
        console.log("- ankit.verma@email.com (Regular User)")

        // Export user IDs for use in other seed files
        return userIds
    } catch (error) {
        console.error("❌ Error seeding platform users:", error)
        throw error
    }
}

// Run the seeding function
if (require.main === module) {
    seedPlatformUsers()
        .then(() => {
            console.log("✅ Platform users seeding completed successfully!")
            process.exit(0)
        })
        .catch((error) => {
            console.error("❌ Platform users seeding failed:", error)
            process.exit(1)
        })
}

seedPlatformUsers()
